### ISSUE TITLE
I got error vocab_words is not define 

### ISSUE THREAD

**Issue by nairaarisa** [pandeyanuradha/Naive-Bayes-from-scratch-in-Python-#1]
Thank you for this repository. It helps me in doing my paper so well. in order to get better understanding on how naive bayes works, I try to run this project again. however, at line [22] I got error vocab_words is not define . so I add vocab_words="". it does not give me any error. but it does not calculate the calculation for each sentiment class. the calculation become 0. I am sorry if this offended you.

**Comment by pandeyanuradha** [comment]
Hey, thanks for pointing that out. I guess I had commented out the part where I had defined vocab_words. I have fixed the issue now, and you can find the updated repo.
FYI, vocab_words won't be an empty string since the words are already present in the dictionary. Please let me know if you have any other queries so that I can close this issue.

**Comment by nairaarisa** [comment]
everything works well. thank you :) May God bless you always.
